version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/ausilio-appflowy"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    directory: "/ausilio-cal-diy"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    directory: "/ausilio-documenso"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    directory: "/ausilio-erpnext"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    directory: "/ausilio-listmonk"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    directory: "/ausilio-openseo"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    directory: "/ausilio-paperclip"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
