version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ausilio-dub_web_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"

  web:
    image: dubco/dub:latest
    restart: on-failure
    environment:
      - PORT=3000
      - NEXTAUTH_URL=http://${DEVICE_DOMAIN_NAME}:8086
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
