services:
  app_proxy:
    environment:
      APP_HOST: ausilio-listmonk_web_1
      APP_PORT: 9000
      PROXY_AUTH_ADD: "false"

  web:
    image: listmonk/listmonk:v6.2.0
    restart: on-failure
    command:
      - sh
      - -c
      - ./listmonk --install --idempotent --yes --config '' && ./listmonk --upgrade --yes --config '' && ./listmonk --config ''
    environment:
      - TZ=Etc/UTC
      - LISTMONK_db__host=listmonk-db
      - LISTMONK_db__port=5432
      - LISTMONK_db__user=listmonk
      - LISTMONK_db__password=${APP_PASSWORD}
      - LISTMONK_db__database=listmonk
      - LISTMONK_db__ssl_mode=disable
      - LISTMONK_app__address=0.0.0.0:9000
      - LISTMONK_app__admin_username=admin
      - LISTMONK_app__admin_password=${APP_PASSWORD}
    depends_on:
      listmonk-db:
        condition: service_healthy
    volumes:
      - ${APP_DATA_DIR}/data:/listmonk/uploads
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:9000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  listmonk-db:
    image: postgres:15-alpine
    restart: on-failure
    environment:
      - POSTGRES_USER=listmonk
      - POSTGRES_PASSWORD=${APP_PASSWORD}
      - POSTGRES_DB=listmonk
    volumes:
      - ${APP_DATA_DIR}/db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U listmonk"]
      interval: 10s
      timeout: 5s
      retries: 5
