version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ausilio-documenso_web_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"

  web:
    image: documenso/documenso:latest
    restart: on-failure
    environment:
      - PORT=3000
      - NEXTAUTH_URL=http://${DEVICE_DOMAIN_NAME}:8085
      - DATABASE_URL=postgresql://documenso:documenso_pass@db:5432/documenso
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: on-failure
    environment:
      - POSTGRES_USER=documenso
      - POSTGRES_PASSWORD=documenso_pass
      - POSTGRES_DB=documenso
    volumes:
      - ${APP_DATA_DIR}/db_data:/var/lib/postgresql/data
